/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.io.IOException;
import java.net.MalformedURLException;

import org.openqa.selenium.WebElement;

public class App {

    public void getGreeting() throws InterruptedException, IOException {

        // Initialize your test class
        //TestCases tests = new TestCases();
        // SearchAmazon search = new SearchAmazon();
        // iFrames text = new iFrames();
        //Bookmyshowlist<WebElement> list = new Bookmyshowlist<>();
        //Automate_post_on_linkedin post = new Automate_post_on_linkedin();
        //Recommended_Movies_Link_Print allLinks= new Recommended_Movies_Link_Print();
        //Imdb_Ratings ratings = new Imdb_Ratings();
        Window_Handlings allHandles = new Window_Handlings();

        // TODO: call your test case functions one after other here

         //tests.testCase01();
        // search.SearchAmazon();
        // text.iFrames();
       // list.Bookmyshowlist();
       //post.Automate_post_on_linkedin();
       //allLinks.Recommended_Movies_Link_Print();
       //ratings.imdb_Ratings();
       allHandles.Window_Handlings();

        // END Tests

         //tests.endTest();
        // End your test by clearning connections and closing browser
        // search.endTest();
        // text.endTest();
        //list.endTest();
        //post.endTest();
        //allLinks.endTest();
        //ratings.endTest();
        allHandles.endTest();
    }

    public static void main(String[] args) throws InterruptedException, IOException {
        new App().getGreeting();
    }
}
